# Basic Docker Compose for running eureka-server

version: '3'

services:
  voila-postgres-db:
    build: ../docker-cucumber/postgres-init
    image: 'postgres:voila'
    container_name: voila-postgres-db
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_USER=voila
      - POSTGRES_DB=voila
      
  eureka-server:
    image: "627006115346.dkr.ecr.ap-south-1.amazonaws.com/voila-eureka-server:0.0.5-SNAPSHOT"
    container_name: voila-eureka-server
    environment:
      - JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m
      - TENANT_DB_URL=jdbc:postgresql://voila-postgres-db:5432/voila-tenant
      - REPLICA_TENANT_DB_URL=jdbc:postgresql://voila-postgres-db:5432/voila-tenant
      - SYSTEM_DB_URL=jdbc:postgresql://voila-postgres-db:5432/voila-system
      - REPLICA_SYSTEM_DB_URL=jdbc:postgresql://voila-postgres-db:5432/voila-system
      - voila_SECURITY_BCRYPT_STRENGTH=4
      - AWS_ACCESS_KEY=access-key
      - AWS_SECRET_KEY=secret-key
      - AWS_REGION=local
      - DISCOVERY_URL=http://voila-eureka-server:8761/eureka
    ports:
      - "0.0.0.0:8761:8761"
    depends_on:
      - "voila-postgres-db"
