server:
   port: ${PORT:8761}
eureka:
   instance:
      hostname: localhost
   client:
      region: default
      serviceUrl:
         defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka
      registerWithEureka: false
      fetchRegistry: false
   server:
      enableSelfPreservation: false
   dashboard:
      enabled: true
      path: /eurekawebui
spring:
   application:
      name: Eureka
   cloud:
      config:
         server:
            prefix: /config
            native:
               search-locations: classpath:/shared #tells spring where to locate the config files
   datasource:
      url: ${TENANT_DB_URL:jdbc:postgresql://127.0.0.1:5432/voila-tenant}
      username: ${TENANT_DB_USER:voila-tenant}
      password: ${TENANT_DB_PASSWORD:pgpassword}
voila:
   security:
      bcryptStrength: ${VOILA_SECURITY_BCRYPT_STRENGTH:-1}