server:  
  port: ${PORT:8761}
    
eureka:  
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false 
spring:
   datasource:
      url: ${TENANT_DB_URL:jdbc:postgresql://127.0.0.1:5432/modiant-tenant}
      username: ${TENANT_DB_USER:voila-tenant}
      password: ${TENANT_DB_PASSWORD:pgpassword}
voila:
  security:
    # the number of log rounds for bcrypt (-1 == strongest; 4 == weakest)
    bcryptStrength: ${MODIANT_SECURITY_BCRYPT_STRENGTH:-1}