server:  
  port: ${PORT:8765}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
  eureka: true

zuul:
  prefix: /api
  routes:
    test: 
      path: /test/**
      serviceId: test-service

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false